# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9934bec716af91746c72a8cddbff4291c2ad57bb041b2c96a61db1b3fdce2154d01ba8d043cb7c2654fe83a40c116be43b3bf47cd7da028012c3a9274f690e46

test:
  secret_key_base: e10759e685b5bbfb02e55c93d3cc5a4e753a9156ca85224f57c505351bdf29b9902a360336b385bbbbbc0c63f45465703db6454fe60ef0f69ac6253696c96d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
